### ISSUE TITLE
Path shows `undefined` after cancelled folder dialogue

### ISSUE THREAD

**Issue by montyanderson** [storjrd/backup#119]
![image](https://user-images.githubusercontent.com/3048503/146413382-656336da-533b-4be5-8023-4bb8cb7eea7b.png)

**Comment by gabedealmeida** [comment]
I can't reproduce this on an m1. Wonder if this is a Linux and/or Windows issue.

**Comment by gabedealmeida** [comment]
Fixed by https://github.com/storjrd/backup/pull/120
