### ISSUE TITLE
`logout` remote method error while attempting to logout

### ISSUE THREAD

**Issue by gabedealmeida** [storjrd/backup#127]
<img width="434" alt="Screen Shot 2022-01-06 at 12 39 36 PM" src="https://user-images.githubusercontent.com/52146328/148426371-3bfe0d65-8bc2-486c-8eeb-40071d4ccfbf.png">

**Comment by montyanderson** [comment]
Should be fixed by https://github.com/storjrd/backup/commit/a8731c0eed2a7b955cbb0b4ca8e53a8c67ef9453
