### ISSUE TITLE
An empty Restic password causes sign in to fail

### ISSUE THREAD

**Issue by upnix** [storjrd/backup#209]
When I started the app on macOS for the first time, I filled in all the fields, but left the "Restic password" blank. Hitting "Sign in", I got a spinner and thought everything was working as expected, but the spinner never stopped. Only after going to the developer console did I see the error (a screenshot is also attached):
```
Error: Password needs to be longer than three characters.
```
The release is v0.200 (I believe, it's from [here](https://github.com/storjrd/backup/releases/tag/v0.200))

_**The error**_
![Screen Shot 2022-02-10 at 8 47 20 AM](https://user-images.githubusercontent.com/6163553/153443722-2c2c35e4-b8b2-4286-9192-580d136b0a2f.png)

_**What I saw**_
![Screen Shot 2022-02-10 at 8 50 55 AM](https://user-images.githubusercontent.com/6163553/153444547-94ccaeb2-8b47-4905-939c-4b0974e5fed9.png)

**Comment by super3** [comment]
@montyanderson We may need just to make Restic password optional to have full compatibility with Restic.

**Comment by montyanderson** [comment]
Fixed by https://github.com/storjrd/backup/commit/a8731c0eed2a7b955cbb0b4ca8e53a8c67ef9453
